require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::SalesController, type: :controller do
  let(:valid_key) {
    user = FactoryGirl.create(:user_2)
    user.auth(user.password)
    valid_key = user.access_key
  }
  
  describe 'GET show' do
    it 'assigns the requested sale as @sale' do
      sale = FactoryGirl.create(:sale)
      get :show, { id: sale.to_param, access_key: valid_key, format: 'json' }
      expect(assigns(:sale)).to eq(sale)
    end
  end

  describe 'POST create' do
    describe 'with single params' do
      describe 'with valid params' do
        it 'creates a new Sale' do
          expect {
            post :create, { sale: FactoryGirl.attributes_for(:sale), access_key: valid_key, format: 'json' }
          }.to change(Sale, :count).by(1)
        end
        it 'assigns a newly created sale in @sales' do
          post :create, { sale: FactoryGirl.attributes_for(:sale), access_key: valid_key, format: 'json' }
          assigns(:sales).each { |s| expect(s).to be_a(Sale) }
        end
      end
      describe 'with invalid params' do
        it 'does not save a new Sale' do
          post :create, { sale: FactoryGirl.attributes_for(:sale, code: 'a'), access_key: valid_key, format: 'json' }
          assigns(:sales).each { |s| expect(s).to be_a_new(Sale) }
        end
      end
    end

    describe 'with multiple params' do
      describe 'with valid params' do
        it 'creates new Sales' do
          sales = []
          num = 10
          num.times { |n| sales.push FactoryGirl.attributes_for(:sale) }

          expect {
            post :create, { sales: sales, access_key: valid_key, format: 'json' }
            assigns(:sales).each { |s| expect(s).to be_a(Sale) }
          }.to change(Sale, :count).by(num)
        end
      end

      describe 'with invalid params' do
        it 'does not save new Sales' do
          sales = []
          num = 10
          num.times { |n| sales.push FactoryGirl.attributes_for(:sale) }
          post :create, { sale: FactoryGirl.attributes_for(:sale, code: 'a'), access_key: valid_key, format: 'json' }
          assigns(:sales).each { |s| expect(s).to be_a_new(Sale) }
        end
      end
    end
  end
 
  describe 'DELETE destroy' do
    it 'destroys the requested sale' do
      sale = FactoryGirl.create(:sale)
      expect {
        delete :destroy, { id: sale.to_param, access_key: valid_key }
      }.to change(Sale, :count).by(-1)
    end
  end

end
